config/routes.rb
NestedModelsExample::Application.routes.draw do
  root :to => 'products#index'

  resources :categories
  resources :products
end

app/models/category.rb
class Category < ActiveRecord::Base
   attr_accessible :description

   has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
   attr_accessible :name, :category_id, :category_attributes

   belongs_to :category   

   accepts_nested_attributes_for :category

   validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   def index
      @products = Product.includes(:category).order(:name)
   end

   def new
      @product = Product.new { |p| p.build_category }
      #@product.build_category
   end

   def create         
      @product = Product.new params_product

      if @product.save
         flash[:notice] = "Product created with successfully!"
         redirect_to products_path      
      else
         render :new
      end
   end

   def edit
      @product = Product.find(params[:id])
   end

   def update
      @product = Product.find(params[:id])

      if @product.udpate_attributes params_product
         flash[:notice] = "Product updated with successfully!"
         redirect_to products_path      
      else
         render :edit
      end
   end

   private
   def params_product
      parameters = params[:product]

      if parameters[:category_attributes] && !parameters[:category_attributes][:description].empty?
         parameters.delete :category_id
      else
         parameters.delete :category_attributes
      end

      parameters
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedModelsExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
   <li><%= link_to "Categories", categories_path %></li>
   <li><%= link_to "Products", products_path %></li>
</ul>
<hr />

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |product_form| %>

<div class="error-messages">
   <% if @product.errors.any? %>

      <ul>
         <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul> 

   <% end %>
</div>

   <%= product_form.fields_for :category do |category_fields| %>

      <p>
         <%= product_form.label :name %>
         <%= product_form.text_field :name %>
      </p>

      <p>
         <%= category_fields.label "create category" %>
         <%= category_fields.text_field :description %>    

         <%= product_form.collection_select :category_id, Category.order(:description), :id, :description, :prompt => "or select here" %>
      </p>

   <% end %>
      
   <p>
      <%= product_form.submit %>
   </p>

<% end %>   

app/views/products/edit.html.erb
<%= render "form" %>

app/views/products/index.html.erb
<h2>Products</h2>

<table>
   <th>name</th>   
   <th>category</th>   

   <% @products.each do |product| %>
      <tr>
         <td><%= product.name %></td>
         <td><%= product.category && product.category.description %></td>
      </tr>
   <% end %>

</table>

<p>
   <%= link_to "New product", new_product_path %>
</p>

app/views/products/new.html.erb
<h2>Create product</h2>
<%= render "form" %>